### ISSUE TITLE
Crashes if Discord isn't open

### ISSUE THREAD

**Issue by BetaKors** [Superredstone/Red_Discord_Presence#1]
The mod crashes the game if Discord isn't open, with the crash report having the following:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'red_discord_presence'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: com.jagrosh.discordipc.exceptions.NoDiscordClientException: No Valid Discord Client was found for this Instance
	at com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:162)
	at com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:344)
	at com.superredstone.red_discord_presence.utils.RichPresenceHandler.connect(RichPresenceHandler.kt:68)
	at com.superredstone.red_discord_presence.RedDiscordPresence.onInitialize(RedDiscordPresence.kt:25)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
```

**Comment by Superredstone** [comment]
Thank you! :D
